# Generated by Django 3.1.2 on 2021-10-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211030_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reccomendation',
            field=models.ManyToManyField(to='main_app.Reccomendation'),
        ),
    ]
