# Generated by Django 3.1.2 on 2021-11-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20211031_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='comment_profiles', to='main_app.profile'),
            preserve_default=False,
        ),
    ]
